
#spring:
#  redis:
#    host: 64.227.90.194
#    port: 6379
#    timeout: 900

cache:
  timeoutSeconds: 150
  redisPort: 6379
  redisHost: 64.227.92.244
  cacheExpiration:
    "customers": 120
    "customer" : 130